language: c

branches:
   only:
      - master

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install libpam0g-dev libcurl4-openssl-dev libssl-dev

compiler:
   - gcc
   - clang

script: make
